server:
  port: 8280
mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml,classpath:/mybatis/mapper/extend/*.xml


spring:
  datasource:
     url: jdbc:mysql://localhost:3306/musicplatform?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
     username: root
     password: root
     driver-class-name: com.mysql.jdbc.Driver
  devtools:
    restart:
      enabled: true
  freemarker:
    cache: false

logging:
  level:
    net/suncaper/demo: debug

