server:
  port: 8280
mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml,classpath:/mybatis/mapper/extend/*.xml


spring:
  datasource:
     url: jdbc:mysql://localhost:3306/scu_project?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
     username: root
     password: 991116ta
     driver-class-name: com.mysql.jdbc.Driver
  devtools:
    restart:
      enabled: true  #设置开启热部署
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效

  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 3000
    # password:
    lettuce:
      poll:
        minIdle: 1
        maxIdle: 10
        maxWait: 3
        maxActive: 8
  mail:
    # 配置 SMTP 服务器地址
    host: smtp.qq.com
    # 发送者邮箱
    username: 2717199940@qq.com
    # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
    password: lgwrxfinbvgndfej
    # 端口号465或587
    port: 587
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    # 配置SSL 加密工厂
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true

logging:
  level:
    com/hwadee/scu: debug

