package com.hwadee.scu.common.domain;

public class MusicList {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_list.id
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_list.listName
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    private String listname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_list.musicName
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    private String musicname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_list.author
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music_list.album
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    private String album;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_list
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    public MusicList(Integer id, String listname, String musicname, String author, String album) {
        this.id = id;
        this.listname = listname;
        this.musicname = musicname;
        this.author = author;
        this.album = album;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_list
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    public MusicList() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_list.id
     *
     * @return the value of music_list.id
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_list.id
     *
     * @param id the value for music_list.id
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_list.listName
     *
     * @return the value of music_list.listName
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    public String getListname() {
        return listname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_list.listName
     *
     * @param listname the value for music_list.listName
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    public void setListname(String listname) {
        this.listname = listname == null ? null : listname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_list.musicName
     *
     * @return the value of music_list.musicName
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    public String getMusicname() {
        return musicname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_list.musicName
     *
     * @param musicname the value for music_list.musicName
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    public void setMusicname(String musicname) {
        this.musicname = musicname == null ? null : musicname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_list.author
     *
     * @return the value of music_list.author
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_list.author
     *
     * @param author the value for music_list.author
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music_list.album
     *
     * @return the value of music_list.album
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    public String getAlbum() {
        return album;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music_list.album
     *
     * @param album the value for music_list.album
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    public void setAlbum(String album) {
        this.album = album == null ? null : album.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_list
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MusicList other = (MusicList) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getListname() == null ? other.getListname() == null : this.getListname().equals(other.getListname()))
            && (this.getMusicname() == null ? other.getMusicname() == null : this.getMusicname().equals(other.getMusicname()))
            && (this.getAuthor() == null ? other.getAuthor() == null : this.getAuthor().equals(other.getAuthor()))
            && (this.getAlbum() == null ? other.getAlbum() == null : this.getAlbum().equals(other.getAlbum()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_list
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getListname() == null) ? 0 : getListname().hashCode());
        result = prime * result + ((getMusicname() == null) ? 0 : getMusicname().hashCode());
        result = prime * result + ((getAuthor() == null) ? 0 : getAuthor().hashCode());
        result = prime * result + ((getAlbum() == null) ? 0 : getAlbum().hashCode());
        return result;
    }
}