package com.hwadee.scu.common.domain;

public class PlaylistNumber {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column playlist_number.id
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column playlist_number.listName
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    private String listname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column playlist_number.playNumber
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    private Integer playnumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table playlist_number
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    public PlaylistNumber(Integer id, String listname, Integer playnumber) {
        this.id = id;
        this.listname = listname;
        this.playnumber = playnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table playlist_number
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    public PlaylistNumber() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column playlist_number.id
     *
     * @return the value of playlist_number.id
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column playlist_number.id
     *
     * @param id the value for playlist_number.id
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column playlist_number.listName
     *
     * @return the value of playlist_number.listName
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    public String getListname() {
        return listname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column playlist_number.listName
     *
     * @param listname the value for playlist_number.listName
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    public void setListname(String listname) {
        this.listname = listname == null ? null : listname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column playlist_number.playNumber
     *
     * @return the value of playlist_number.playNumber
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    public Integer getPlaynumber() {
        return playnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column playlist_number.playNumber
     *
     * @param playnumber the value for playlist_number.playNumber
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    public void setPlaynumber(Integer playnumber) {
        this.playnumber = playnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table playlist_number
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PlaylistNumber other = (PlaylistNumber) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getListname() == null ? other.getListname() == null : this.getListname().equals(other.getListname()))
            && (this.getPlaynumber() == null ? other.getPlaynumber() == null : this.getPlaynumber().equals(other.getPlaynumber()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table playlist_number
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getListname() == null) ? 0 : getListname().hashCode());
        result = prime * result + ((getPlaynumber() == null) ? 0 : getPlaynumber().hashCode());
        return result;
    }
}