package com.hwadee.scu.common.domain;

public class XwzydrComNum {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xwzydr_com_num.id
     *
     * @mbg.generated Tue Jun 15 18:35:16 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xwzydr_com_num.word
     *
     * @mbg.generated Tue Jun 15 18:35:16 CST 2021
     */
    private String word;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xwzydr_com_num.num
     *
     * @mbg.generated Tue Jun 15 18:35:16 CST 2021
     */
    private Integer num;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xwzydr_com_num
     *
     * @mbg.generated Tue Jun 15 18:35:16 CST 2021
     */
    public XwzydrComNum(Integer id, String word, Integer num) {
        this.id = id;
        this.word = word;
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xwzydr_com_num
     *
     * @mbg.generated Tue Jun 15 18:35:16 CST 2021
     */
    public XwzydrComNum() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xwzydr_com_num.id
     *
     * @return the value of xwzydr_com_num.id
     *
     * @mbg.generated Tue Jun 15 18:35:16 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xwzydr_com_num.id
     *
     * @param id the value for xwzydr_com_num.id
     *
     * @mbg.generated Tue Jun 15 18:35:16 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xwzydr_com_num.word
     *
     * @return the value of xwzydr_com_num.word
     *
     * @mbg.generated Tue Jun 15 18:35:16 CST 2021
     */
    public String getWord() {
        return word;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xwzydr_com_num.word
     *
     * @param word the value for xwzydr_com_num.word
     *
     * @mbg.generated Tue Jun 15 18:35:16 CST 2021
     */
    public void setWord(String word) {
        this.word = word == null ? null : word.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xwzydr_com_num.num
     *
     * @return the value of xwzydr_com_num.num
     *
     * @mbg.generated Tue Jun 15 18:35:16 CST 2021
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xwzydr_com_num.num
     *
     * @param num the value for xwzydr_com_num.num
     *
     * @mbg.generated Tue Jun 15 18:35:16 CST 2021
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xwzydr_com_num
     *
     * @mbg.generated Tue Jun 15 18:35:16 CST 2021
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        XwzydrComNum other = (XwzydrComNum) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getWord() == null ? other.getWord() == null : this.getWord().equals(other.getWord()))
            && (this.getNum() == null ? other.getNum() == null : this.getNum().equals(other.getNum()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xwzydr_com_num
     *
     * @mbg.generated Tue Jun 15 18:35:16 CST 2021
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getWord() == null) ? 0 : getWord().hashCode());
        result = prime * result + ((getNum() == null) ? 0 : getNum().hashCode());
        return result;
    }
}