package com.hwadee.scu.mapper;

import com.hwadee.scu.common.domain.CdComments;
import com.hwadee.scu.common.domain.CdCommentsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CdCommentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cd_comments
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    long countByExample(CdCommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cd_comments
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    int deleteByExample(CdCommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cd_comments
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cd_comments
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    int insert(CdComments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cd_comments
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    int insertSelective(CdComments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cd_comments
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    List<CdComments> selectByExample(CdCommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cd_comments
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    CdComments selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cd_comments
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    int updateByExampleSelective(@Param("record") CdComments record, @Param("example") CdCommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cd_comments
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    int updateByExample(@Param("record") CdComments record, @Param("example") CdCommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cd_comments
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    int updateByPrimaryKeySelective(CdComments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cd_comments
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    int updateByPrimaryKey(CdComments record);
}