package com.hwadee.scu.mapper;

import com.hwadee.scu.common.domain.CdComNum;
import com.hwadee.scu.common.domain.CdComNumExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface CdComNumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cd_com_num
     *
     * @mbg.generated Tue Jun 15 18:35:16 CST 2021
     */
    long countByExample(CdComNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cd_com_num
     *
     * @mbg.generated Tue Jun 15 18:35:16 CST 2021
     */
    int deleteByExample(CdComNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cd_com_num
     *
     * @mbg.generated Tue Jun 15 18:35:16 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cd_com_num
     *
     * @mbg.generated Tue Jun 15 18:35:16 CST 2021
     */
    int insert(CdComNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cd_com_num
     *
     * @mbg.generated Tue Jun 15 18:35:16 CST 2021
     */
    int insertSelective(CdComNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cd_com_num
     *
     * @mbg.generated Tue Jun 15 18:35:16 CST 2021
     */
    List<CdComNum> selectByExample(CdComNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cd_com_num
     *
     * @mbg.generated Tue Jun 15 18:35:16 CST 2021
     */
    CdComNum selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cd_com_num
     *
     * @mbg.generated Tue Jun 15 18:35:16 CST 2021
     */
    int updateByExampleSelective(@Param("record") CdComNum record, @Param("example") CdComNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cd_com_num
     *
     * @mbg.generated Tue Jun 15 18:35:16 CST 2021
     */
    int updateByExample(@Param("record") CdComNum record, @Param("example") CdComNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cd_com_num
     *
     * @mbg.generated Tue Jun 15 18:35:16 CST 2021
     */
    int updateByPrimaryKeySelective(CdComNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cd_com_num
     *
     * @mbg.generated Tue Jun 15 18:35:16 CST 2021
     */
    int updateByPrimaryKey(CdComNum record);

    @Select("select *from cd_com_num")
    List<CdComNum> findAllCd();
}