package com.hwadee.scu.mapper;

import com.hwadee.scu.common.domain.GdsnaqgsComNum;
import com.hwadee.scu.common.domain.GdsnaqgsComNumExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface GdsnaqgsComNumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gdsnaqgs_com_num
     *
     * @mbg.generated Tue Jun 15 18:35:16 CST 2021
     */
    long countByExample(GdsnaqgsComNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gdsnaqgs_com_num
     *
     * @mbg.generated Tue Jun 15 18:35:16 CST 2021
     */
    int deleteByExample(GdsnaqgsComNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gdsnaqgs_com_num
     *
     * @mbg.generated Tue Jun 15 18:35:16 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gdsnaqgs_com_num
     *
     * @mbg.generated Tue Jun 15 18:35:16 CST 2021
     */
    int insert(GdsnaqgsComNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gdsnaqgs_com_num
     *
     * @mbg.generated Tue Jun 15 18:35:16 CST 2021
     */
    int insertSelective(GdsnaqgsComNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gdsnaqgs_com_num
     *
     * @mbg.generated Tue Jun 15 18:35:16 CST 2021
     */
    List<GdsnaqgsComNum> selectByExample(GdsnaqgsComNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gdsnaqgs_com_num
     *
     * @mbg.generated Tue Jun 15 18:35:16 CST 2021
     */
    GdsnaqgsComNum selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gdsnaqgs_com_num
     *
     * @mbg.generated Tue Jun 15 18:35:16 CST 2021
     */
    int updateByExampleSelective(@Param("record") GdsnaqgsComNum record, @Param("example") GdsnaqgsComNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gdsnaqgs_com_num
     *
     * @mbg.generated Tue Jun 15 18:35:16 CST 2021
     */
    int updateByExample(@Param("record") GdsnaqgsComNum record, @Param("example") GdsnaqgsComNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gdsnaqgs_com_num
     *
     * @mbg.generated Tue Jun 15 18:35:16 CST 2021
     */
    int updateByPrimaryKeySelective(GdsnaqgsComNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gdsnaqgs_com_num
     *
     * @mbg.generated Tue Jun 15 18:35:16 CST 2021
     */
    int updateByPrimaryKey(GdsnaqgsComNum record);

    @Select("select *from gdsnaqgs_com_num")
    List<GdsnaqgsComNum> selectAll();
}