package com.hwadee.scu.mapper;

import com.hwadee.scu.common.domain.GdsnaqgsComments;
import com.hwadee.scu.common.domain.GdsnaqgsCommentsExample;
import java.util.List;

import com.hwadee.scu.common.domain.entity.Comment;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface GdsnaqgsCommentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gdsnaqgs_comments
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    long countByExample(GdsnaqgsCommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gdsnaqgs_comments
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    int deleteByExample(GdsnaqgsCommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gdsnaqgs_comments
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gdsnaqgs_comments
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    int insert(GdsnaqgsComments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gdsnaqgs_comments
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    int insertSelective(GdsnaqgsComments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gdsnaqgs_comments
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    List<GdsnaqgsComments> selectByExample(GdsnaqgsCommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gdsnaqgs_comments
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    GdsnaqgsComments selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gdsnaqgs_comments
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    int updateByExampleSelective(@Param("record") GdsnaqgsComments record, @Param("example") GdsnaqgsCommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gdsnaqgs_comments
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    int updateByExample(@Param("record") GdsnaqgsComments record, @Param("example") GdsnaqgsCommentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gdsnaqgs_comments
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    int updateByPrimaryKeySelective(GdsnaqgsComments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gdsnaqgs_comments
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    int updateByPrimaryKey(GdsnaqgsComments record);
    @Select("SELECT Hour(time) as Hour,count(*) as Count FROM gdsnaqgs_comments GROUP BY HOUR ORDER BY Hour")
    List<Comment> getComments();
}