package com.hwadee.scu.mapper;

import com.hwadee.scu.common.domain.MusicList;
import com.hwadee.scu.common.domain.MusicListExample;
import java.util.List;

import com.hwadee.scu.common.domain.entity.PlayList;
import com.hwadee.scu.common.domain.entity.Singer;
import com.hwadee.scu.common.domain.entity.Song;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface MusicListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_list
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    long countByExample(MusicListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_list
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    int deleteByExample(MusicListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_list
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_list
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    int insert(MusicList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_list
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    int insertSelective(MusicList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_list
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    List<MusicList> selectByExample(MusicListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_list
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    MusicList selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_list
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    int updateByExampleSelective(@Param("record") MusicList record, @Param("example") MusicListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_list
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    int updateByExample(@Param("record") MusicList record, @Param("example") MusicListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_list
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    int updateByPrimaryKeySelective(MusicList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_list
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    int updateByPrimaryKey(MusicList record);

    @Select("select listName ,count(musicName) as count from music_list group by listName order by count desc limit 10")
    List<PlayList> selectListSong();

    @Select("select musicName ,count(musicName) as times from music_list group by musicName order by times desc limit 10")
    List<Song> getSong();

    @Select("select author ,count(author) as times from music_list group by author order by times desc limit 10")
    List<Singer> getSinger();
}