package com.hwadee.scu.mapper;

import com.hwadee.scu.common.domain.MusicList;
import com.hwadee.scu.common.domain.MusicListExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MusicListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_list
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    long countByExample(MusicListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_list
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    int deleteByExample(MusicListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_list
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_list
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    int insert(MusicList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_list
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    int insertSelective(MusicList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_list
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    List<MusicList> selectByExample(MusicListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_list
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    MusicList selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_list
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    int updateByExampleSelective(@Param("record") MusicList record, @Param("example") MusicListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_list
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    int updateByExample(@Param("record") MusicList record, @Param("example") MusicListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_list
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    int updateByPrimaryKeySelective(MusicList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_list
     *
     * @mbg.generated Tue Jun 15 11:22:48 CST 2021
     */
    int updateByPrimaryKey(MusicList record);
}