package com.hwadee.scu.mapper;

import com.hwadee.scu.common.domain.QflComNum;
import com.hwadee.scu.common.domain.QflComNumExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface QflComNumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qfi_com_num
     *
     * @mbg.generated Tue Jun 15 18:35:16 CST 2021
     */
    long countByExample(QflComNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qfi_com_num
     *
     * @mbg.generated Tue Jun 15 18:35:16 CST 2021
     */
    int deleteByExample(QflComNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qfi_com_num
     *
     * @mbg.generated Tue Jun 15 18:35:16 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qfi_com_num
     *
     * @mbg.generated Tue Jun 15 18:35:16 CST 2021
     */
    int insert(QflComNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qfi_com_num
     *
     * @mbg.generated Tue Jun 15 18:35:16 CST 2021
     */
    int insertSelective(QflComNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qfi_com_num
     *
     * @mbg.generated Tue Jun 15 18:35:16 CST 2021
     */
    List<QflComNum> selectByExample(QflComNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qfi_com_num
     *
     * @mbg.generated Tue Jun 15 18:35:16 CST 2021
     */
    QflComNum selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qfi_com_num
     *
     * @mbg.generated Tue Jun 15 18:35:16 CST 2021
     */
    int updateByExampleSelective(@Param("record") QflComNum record, @Param("example") QflComNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qfi_com_num
     *
     * @mbg.generated Tue Jun 15 18:35:16 CST 2021
     */
    int updateByExample(@Param("record") QflComNum record, @Param("example") QflComNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qfi_com_num
     *
     * @mbg.generated Tue Jun 15 18:35:16 CST 2021
     */
    int updateByPrimaryKeySelective(QflComNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qfi_com_num
     *
     * @mbg.generated Tue Jun 15 18:35:16 CST 2021
     */
    int updateByPrimaryKey(QflComNum record);

    @Select("select *from qfi_com_num")
    List<QflComNum> findAllQfl();
}